### ISSUE TITLE
Details are not prefilled when clicking on "Create product"

### ISSUE THREAD

**Issue by afonsoc12** [Forceu/barcodebuddy#103]
Hello,
I am fairly knew to this app and I am sorry if it is just me who did not get this right, but what is the point of the "Create product" button just open grocy?
Couldn't this be enhanced by making use of the API to parse the scanned information instead? However, I am not sure if this is possible since `PUT /objects/{entity}/{objectId}` is only capable of editing
Version: Docker f0rc3/barcodebuddy-docker:arm64v8-v1.6.5.0
Thanks

**Comment by Forceu** [comment]
Thanks for the issue, before Grocy 3.0 this used to enter the name of the product and the barcode... it seems that starting with 3.0 this is not done by the Grocy interface anymore, I will have a look at it.

**Comment by Forceu** [comment]
So with the current commit the name is entered again.

Regarding prefilling other items like calories etc: That would be quite a lot of effort, as Grocy itself would need to be changed and all lookup providers would need to be adjusted as well.

A lot of people including me also use generic products in Grocy (eg. "Chocolate" instead of "[Brand] Chocolate"). That way it makes it a lot easier to manage the products, but obivously you can't use fields like calories.
