### ISSUE TITLE
New Lookup Source

### ISSUE THREAD

**Issue by heig** [Forceu/barcodebuddy#167]
Hi, I noticed, that many EDEKA Products are not in the databases that you query. Therefore I created a database of over 7.000 EDEKA Products with more than 15.000 EANs that I would like to share with the community. 

Unfortunately I was not able to insert the new Lookup Source myself. Would you like to add my source? 

URL: https://gc-lb.heig.net/eanlookup?ean=4311501655184

The response is a JSON: 

```
[
   {
      "productId":42,
      "Products":{
         "brand":"Gut & G\u00fcnstig",
         "name":"Skyr pur 500g",
         "contents":"0.5 kg"
      }
   }
]
```

Henning

**Comment by Forceu** [comment]
Hi Henning, thank you very much! Will the data be updated in the future?
And would it be possible that you send me a copy of the database to edeka@bulling-it.de so I can integrate it with Barcode Buddy Federation? That way there would be no need to add another lookup provider.

**Comment by heig** [comment]
> Hi Henning, thank you very much! Will the data be updated in the future? And would it be possible that you send me a copy of the database to [edeka@bulling-it.de](mailto:edeka@bulling-it.de) so I can integrate it with Barcode Buddy Federation? That way there would be no need to add another lookup provider.

Hi Marc, 
yes the data will be updated on a regular basis. I will setup a scheduled job to keep it in sync. Through an APP API of Edeka I have access to the products and can keep it updated. 
But I can also send you a database dump if you prefer, and we keep it at the current version.

**Comment by Forceu** [comment]
Great! In that case I will add the lookup provider in the coming days. Would it maybe be possible to have an API endpoint protected with a secret key, so the Federation server could sync with your data automatically? I would be happy to help you with that

**Comment by heig** [comment]
Sure, No Problem. I can provide you a JSON with all Products & EANs. I'll send it to the e-mail above mentioned.

**Comment by Forceu** [comment]
Thanks, I added the import to the Federation Server, which now syncs the database daily. :)

I noted that the delay of your server for a lookup is more than a second, therefore I think it would be better if the lookup is done with the Federation Server instead of an additional lookup provider in Barcode Buddy, as the response time there is around 50-150ms.

If you would like to see the lookup source included however, let me know and I will add it to Barcode Buddy!

Oh and I noticed that the private API endpoint only returns 1000 items (I sent you an email in that regard), I suppose this is a bug?
