### ISSUE TITLE
Autocreation of Products

### ISSUE THREAD

**Issue by sgtsilver** [Forceu/barcodebuddy#20]
Hey there, I've ran into an a big showstopper using your tool - why does it not create new products even when the UPC is recognized? If I have to add all the Products manually, what's the point of Barcodebuddy recognizing the UPC but dosen't give the product any meta data like producer or something or you can't create a new product from a recognized UPC?

Is something wrong in my settings that barcodebuddy is not allowed to add new products into grocy?
Please tell me where to check if so.

**Comment by Forceu** [comment]
Thank you for your feedback! An autocreation function is not implemented, as most users would not benefit from it. I think most people use general term (eg. "Cookies" instead of having a product for every different brand/packaging).

Also required fields like Storage Location, Unit, etc cannot be filled out automatically.

However there is a "Create Product" button on the main page, which inserts the name and barcode upon clicking on it.
