### ISSUE TITLE
Feature Request: Home Assistant Addon

### ISSUE THREAD

**Issue by zsarnett** [Forceu/barcodebuddy#47]
It would be great if adding this for use with the Grocy Addon with Home Assistant was as easy as adding this as an addon and linking the two together.

**Comment by Forceu** [comment]
Thanks for your feedback! I already thought about it and once I have enough time I will have a look at it.

**Comment by cyberjacob** [comment]
@zsarnett Can this not already be done with HASS' `panel_iframe` component? Or are you looking to have it run in hass.io's docker management?

**Comment by miniksa** [comment]
@Forceu, I really, really want this. Do you mind if I try to figure out how to make it happen? I've been playing around trying to figure out how to make Home Assistant Add-ons and would like to try to adapt the `barcodebuddy-docker` repo to build a HA-compatible image.

**Comment by Forceu** [comment]
Yes that would be great! Do you want to create your own repo or should I open one and add you as a maintainer?

**Comment by miniksa** [comment]
> Yes that would be great! Do you want to create your own repo or should I open one and add you as a maintainer?

I think the second option is better. `forceu/barcodebuddy-hassio` or something. Makes more sense to me to keep them all in the same place.

I've already been making some progress in a fork on `miniksa/barcodebuddy-docker`, but I can switch that over.

Also, do you have any sort of icon/logo assets already made that I could use for the extension? I know the `barcodebuddy-android` app has a display icon, but I couldn't find it in my extremely brief look into that repo.

**Comment by cyberjacob** [comment]
Would there be a particular reason to split the hass.io implementation into a separate repo? The [relevant documentation](https://developers.home-assistant.io/docs/add-ons/tutorial) suggests that adding a few files to the existing dockerfile should be enough.

**Comment by miniksa** [comment]
I was hoping to use the same base as the other hassio add-ons and hopefully make whatever changes necessary to the image to have it integrate better without tampering with the existing docker distributions. I don't mind putting it in a subfolder of the existing Barcode buddy-docker or something.

I just don't want to be on the hook for messing up the existing image someone is using.

**Comment by miniksa** [comment]
Additionally, I looked into this further this afternoon. No, it's not really the same Docker container. To be fully "in" with the whole Home Assistant environment, especially for the Ingress feature, we'll need all sorts of different configuration files than from the standard Docker image. So whether that means it's its own folder in `barcodebuddy-docker` or is just split out into `barcodebuddy-hassio` doesn't matter to me. But it's going to end up more different than "just a few configs added in to the existing Dockerfile".

**Comment by miniksa** [comment]
Well... there are options here. I tried it the other way. Instead of making it integrate super nice into the UI and everything with ingress, I just did barely enough to make it run by adding the configs. And it does.

It doesn't show in the Grocy UI on the side and doesn't have any actual integration with Hass.io... but it is running on its Docker instance and exposes a port.

We could just start from there before making it more integrated/complicated.

![image](https://user-images.githubusercontent.com/18221333/83364534-be184d00-a356-11ea-8bfd-c24df6abad7c.png)
![image](https://user-images.githubusercontent.com/18221333/83364536-c40e2e00-a356-11ea-916b-8dcbd1a8ca9a.png)
![image](https://user-images.githubusercontent.com/18221333/83364538-c83a4b80-a356-11ea-9dfc-417b40b40bce.png)
![image](https://user-images.githubusercontent.com/18221333/83364542-d5573a80-a356-11ea-9c81-b511fc1b3cb1.png)
![image](https://user-images.githubusercontent.com/18221333/83364637-7ba34000-a357-11ea-8129-175c5789b737.png)


Issues I see so far with this:
1. Need the ability to set and pass in configuration options to ignore SSL cert root... Barcode Buddy doesn't like my cert and I need to set this.
2. Likely want to use the Home Assistant docker container base, not the lsiobase. 
- Using the HA container base means it doesn't work outside HA. Using just the configs against lsiobase means it almost just works by dumping the configs next to the existing barcodebuddy-docker Dockerfile.
- Using the HA container base means the `abc` user isn't there. Most of the setup scripts for `barcodebuddy-docker` are messing around with that user. I think it's an `nginx` user for the hass base add-on container. 
3. Probably want to move it to Ingress so it shows as a nice sidebar in the Home Assistant UI. (This is weird because it's a wsserver.php and I don't know how to do that with nginx... I'd have to dig. The way I wanted to do this was to mock addon-grocy, but that uses index.php instead, not a websocket server.)
4. No idea how I'm going to get the USB device connected through here. However, I did figure out that NodeRed with Hass.io can just get the USB input and use the Barcode Buddy API to post the input to Barcode Buddy which then posts through to the Grocy API. It's very hokey but it works...

**Comment by Forceu** [comment]
Thanks a lot for your contribution! I created a new repo https://github.com/Forceu/barcodebuddy-homeassistant and sent you an invite. I also uploaded the logo to this repo.

> Need the ability to set and pass in configuration options to ignore SSL cert root... Barcode Buddy doesn't like my cert and I need to set this.

You can override all options and configs with environment variables, see documentation: https://barcodebuddy-documentation.readthedocs.io/en/latest/advanced.html#environment-variables

That way you could also automatically set the Grocy URL (and API key if there is a way to read it out).

> Using the HA container base means the abc user isn't there. Most of the setup scripts for barcodebuddy-docker are messing around with that user.

This is the default nginx user on the Isolinux image. Personally I don't like the name and could change it to something else, and it probably would not break permissions when upgrading, as it is the same user ID.

> wsserver.php 
This is the websocket server, which needs to be started as a separate process. 

> No idea how I'm going to get the USB device connected through here.
This could be rather tricky, as I would assume that a lot of Hass.io users do not have in-depth Linux knowledge. I found the [following plugin](https://www.npmjs.com/package/linux-input-device) for nodered which should do the trick. But you are right, it is not ideal, maybe we find a different solution for that. In the end, root rights are probably needed for that though.

Again, thank you for your help! If I can assist you with anything, let me know!

**Comment by miniksa** [comment]
Thanks @Forceu, I'll start making some pushes to that one to get it set up in my next batch of free time. 

The one big thing I could use assistance with on it, once I get it bootstrapped, is trying to get the nginx configuration for the "Ingress" connection where Home Assistant embeds the webpages within its own portal. I think it's effectively a reverse-proxy thing (for which you have an example at https://github.com/Forceu/barcodebuddy/blob/master/example/nginxReverseProxy.conf), but it's been so long since I've done any web stuff and when I did, I don't think nginx was even the popular thing at the time. I'll try to give it a start, but I'll probably be asking for help once I wander outside my 15-year outdated PHP + Apache knowledge.

**Comment by fgibaux** [comment]
Hi, I would really love this feature as well and I'm happy to see there is some work started on it, thank you! Unfortunately I can't find much time to help at the moment.

for the USB access in the docker, looks like there is a device and/or autoUART option in the configuration [here](https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config) which could help but I appreciate can be more down the line.

HTH

**Comment by miniksa** [comment]
Haven't forgotten about this. I've just not had any free time to work on it. Hopefully in the next few days I'll have an initial push to `Forceu/barcodebuddy-homeassistant` of at least what was working above.

**Comment by miniksa** [comment]
OK, I'm still messing around here. https://github.com/miniksa/barcodebuddy-docker has been pushed with something that almost sort of works. I'm likely done for the day but I hope to keep making progress when my time allows.

Unfortunately, I'm mostly a clown when it comes to Linux since I'm working on like 10-15 year old knowledge and a lot of my stuff looks like it's assembled by a CS201 student who barely knows what bash is. Hopefully someone else can help me be less bad in that.

Anyway, it works inside Home Assistant as an add-on. Here's the steps/caveats if you want to see what it looks like as a super alpha.

## Step 0A:
- Go to Grocy add-on in Home Assistant Supervisor Add-Ons. Go to its config and give it a real port number.
![image](https://user-images.githubusercontent.com/18221333/86184833-c7c5d980-bae9-11ea-82db-c74db1a3ab29.png)
I haven't figured out Ingress or sharing between containers yet.

## Step 0B:
- Go to Grocy and make an API key
![image](https://user-images.githubusercontent.com/18221333/86184871-df04c700-bae9-11ea-96fb-caa7a9913bb8.png)

## Step 0C:
- If you are using AdGuard Home or Pi-Hole add-ons and you have not set a static IP address and DNS into your Home Assistant device, then you need to do that. 

**WARNING: Making your router hand out a fixed IP via DHCP to the device DOES NOT COUNT.**

I did this with the `nmcli` method from the system base itself on both a HassOS install as well as a Raspbian Lite install (with Home Assistant Supervised). See: https://tech.borpin.co.uk/2018/10/18/using-nmcli-to-set-a-static-ipv4-address-in-hass-io/
 
**IF YOU FAIL TO DO THIS, THE HOME ASSISTANT SUPERVISOR WILL PROBABLY BE UNABLE TO BUILD THE CONTAINER ON YOUR DEVICE. SOMETHING ABOUT DNS RESOLUTION GOES HAYWIRE WHEN IT IS ALSO RUNNING ADGUARD/PIHOLE.**

## Step 1:
In the Supervisor 
![image](https://user-images.githubusercontent.com/18221333/86184429-0eff9a80-bae9-11ea-9dd0-a161f516331b.png)
Go to the Add-on store tab 
![image](https://user-images.githubusercontent.com/18221333/86184449-1a52c600-bae9-11ea-927f-144f69d3338a.png)
And click the ... in the top right corner. 
![image](https://user-images.githubusercontent.com/18221333/86184467-2179d400-bae9-11ea-9215-2b44f0bc0700.png)
Choose `Repositories` 
![image](https://user-images.githubusercontent.com/18221333/86184494-322a4a00-bae9-11ea-9fef-8b4b888bbf5a.png)
Then at the bottom, in Add repository 
![image](https://user-images.githubusercontent.com/18221333/86184510-3a828500-bae9-11ea-93e1-798c8760f793.png)
Add `https://github.com/miniksa/barcodebuddy-docker`
![image](https://user-images.githubusercontent.com/18221333/86184531-43735680-bae9-11ea-91a1-eb99cc9d828d.png)
And click ADD.

## Step 2:
The `Barcode Buddy for Grocy` add-on will show up in the list.
![image](https://user-images.githubusercontent.com/18221333/86184591-5dad3480-bae9-11ea-8ebd-c357c3137776.png)
Click it. It will open the add-on page.
![image](https://user-images.githubusercontent.com/18221333/86185505-525b0880-baeb-11ea-8f46-8901d35b0e70.png)
Click INSTALL in the lower left.
![image](https://user-images.githubusercontent.com/18221333/86185516-571fbc80-baeb-11ea-8b44-51704c3c2f44.png)
It will bagel for a bit. You can check the status of it back in Supervisor under the System tab at the top. Then you should see this when it's installed (or F5 refresh)
![image](https://user-images.githubusercontent.com/18221333/86184622-6a318d00-bae9-11ea-824a-cd2a9ed45080.png)
Go to Configuration at the top 
![image](https://user-images.githubusercontent.com/18221333/86184645-73baf500-bae9-11ea-9150-52389f93190e.png)
And set your config. 
![image](https://user-images.githubusercontent.com/18221333/86184668-7fa6b700-bae9-11ea-8608-94e3b99a0ba7.png)
Press SAVE in the lower right corner.
![image](https://user-images.githubusercontent.com/18221333/86184707-8fbe9680-bae9-11ea-8384-9d7e5b2528dd.png)

## Step 3:
 Go back to Info on the top
![image](https://user-images.githubusercontent.com/18221333/86184729-9a792b80-bae9-11ea-9d23-d67d6b061289.png)
And click START in the lower left.
![image](https://user-images.githubusercontent.com/18221333/86184738-a06f0c80-bae9-11ea-913a-18bf8d6245d5.png)
After it grinds a bit, it should refresh (or f5 the page) and click OPEN WEB UI in the lower right.
![image](https://user-images.githubusercontent.com/18221333/86185067-563a5b00-baea-11ea-93d0-564167a011a0.png)

## Step 4:
Put the Grocy API URL and API Key in. This is where that port number to your HA device comes in (`http://yourhadevice:port/api`) and the API key.
![image](https://user-images.githubusercontent.com/18221333/86185096-64887700-baea-11ea-8985-65f4c2d6367e.png)

## Step 5:
Go nuts.
![image](https://user-images.githubusercontent.com/18221333/86185312-e5e00980-baea-11ea-8e59-620f7c602b89.png)

I need to clean it up a lot before it should be pushed.
- The readme needs to be fixed completely for the new environment.
- I need to remove a bunch of the junk I stole from https://github.com/hassio-addons/addon-grocy when I was trying to make it work like the Grocy add-on. (I pivoted to just adapt the existing https://github.com/Forceu/barcodebuddy-docker instead by adding stuff to it for HA support instead of replatforming it on the hassio-addons base image.)
- I need to put the rest of the settings in.
- I probably need to install the settings in a less dumb way than by `sed` replacing values in the config.php file before the thing starts as a part of the container init. (I tried environment variables and the fact that I've never used nginx and haven't used PHP since version 4/5 is really sticking out.)
- Real images should probably be built/published instead of forcing the HASS supervisor to build it (because of the DNS snafu that can happen rather easily.)
- I believe it's forgetting the Grocy API URL and API Key on every restart/update. Should probably make that persistent at least.

Things I haven't tested:
- The SCREEN thing. It looks like it works, but that's not how I use Barcode Buddy so I haven't run down that road yet.

Things that don't work:
- Actual barcode readers connected as devices straight in. I'm doing something weird with Home Assistant's `keyboard_remote` library + the Node Red add-on to capture all of the input and preprocess it before I send it to Barcode Buddy's API via Node-Red. I do that so I can make it speak the results of the Barcode Buddy API calls out my home speakers as well as relay some of the information to my Todoist shopping list.

**Comment by Forceu** [comment]
Thank you very much for your work on this project! Yes, it is probably a good idea to modify the existing docker image instead of creating a new one from scratch.

Environment variables can be inserted in the Nginx config (would be the easiest way to do for those that are always required anyways), simply change https://github.com/miniksa/barcodebuddy-docker/blob/master/root/defaults/default - in the `location .php` block you can insert variables by adding a line similar to this:

`fastcgi_param BBUDDY_DISABLE_AUTHENTICATION 'true';`

> I believe it's forgetting the Grocy API URL and API Key on every restart/update. Should probably make that persistent at least.

Okay that is weird, are any other configurations saved? It might be that HASS is not saving the configuration to a persistent docker storage volume.

**Comment by c1xx** [comment]
Hi there,

thank you very much for this addon, I installed it and now I try to make it accessible via my duckdns hostname. Portforwarding is active on my router, but I can't access BarcodeBuddy from "outside".

What I'm doing wrong?

**Comment by tom-winkler** [comment]
> 
> 
> Thanks a lot for your contribution! I created a new repo https://github.com/Forceu/barcodebuddy-homeassistant and sent you an invite. I also uploaded the logo to this repo.
> 
> > Need the ability to set and pass in configuration options to ignore SSL cert root... Barcode Buddy doesn't like my cert and I need to set this.
> 
> You can override all options and configs with environment variables, see documentation: https://barcodebuddy-documentation.readthedocs.io/en/latest/advanced.html#environment-variables
> 
> That way you could also automatically set the Grocy URL (and API key if there is a way to read it out).
> 
> > Using the HA container base means the abc user isn't there. Most of the setup scripts for barcodebuddy-docker are messing around with that user.
> 
> This is the default nginx user on the Isolinux image. Personally I don't like the name and could change it to something else, and it probably would not break permissions when upgrading, as it is the same user ID.
> 
> > wsserver.php
> 
> This is the websocket server, which needs to be started as a separate process.
> 
> No idea how I'm going to get the USB device connected through here.
> This could be rather tricky, as I would assume that a lot of Hass.io users do not have in-depth Linux knowledge. I found the [following plugin](https://www.npmjs.com/package/linux-input-device) for nodered which should do the trick. But you are right, it is not ideal, maybe we find a different solution for that. In the end, root rights are probably needed for that though.
> 
> Again, thank you for your help! If I can assist you with anything, let me know!

@miniksa I did an initial pull request - mainly motivated by an up-to-date barcode buddy. Have a look!

**Comment by Forceu** [comment]
Thanks to @tom-winkler the repo is now populated and can be used. :)

**Comment by miniksa** [comment]
Wow @tom-winkler, thanks for picking this up and carrying it across the finish line!

I was super gung-ho about this last summer when I was still at home 24/7, but then I forgot about it as the year changed and things partially reopened again and I had different responsibilities. 

I really appreciate you getting it done!
