### ISSUE TITLE
Screen does not update with scans, but codes setting mode work

### ISSUE THREAD

**Issue by Kylespamaccoun7** [Forceu/barcodebuddy#63]
Hi,

The screen.php shows nothing when I scan products.  It does responds to scans adjusting the set-mode, though.

On the overview and in the log, product scans show up, and if I adjust the set-mode, scans will consume, purchase, add to shopping list,etc. Everything works perfect and is reflected in grocy. 

I've been having this issue since installation a few days ago. Running on an ubuntu vm, and I made sure I pulled the latest docker version this morning. I've reviewed the docker installation instructions and available issues, but I could not find anything on what would cause or how to resolve. 

Thank you!
(screenshot attached).

![screen_php screenshot](https://user-images.githubusercontent.com/46274294/81092656-cdba8800-8eb5-11ea-82d1-970066d28794.png)

**Comment by bsmout** [comment]
Same issue here. Just did a bare metal install on a Raspberry Pi.

**Comment by Forceu** [comment]
Thank you for your feedback! So basically the barcodes go through, but are not displayed on the screen module?

What version are you using (Docker, stable or unstable)? Also what webserver are you using?

**Comment by bsmout** [comment]
Yes, barcodes go thru. Scanning barcodes to switch modes (Consume/Purchase/...) works in screen but product barcodes don't show up in screen. I'm using a git clone (unstable) on a Raspberry pi with Nginx.

**Comment by Forceu** [comment]
Since the update from 1.4 to 1.5 we had some changes, including removing websockets for external communication (you still need to start the websocket server however).

Have a look at the updated example nginx file, is it similar to yours? https://github.com/Forceu/barcodebuddy/blob/master/example/nginxConfiguration.conf

Also have you restarted the websocket server after updating Barcode Buddy?

**Comment by lpfann** [comment]
I have the same problem and tried some debugging a few days ago but gave up because JS or PHP are not really in my skillset.

First I had the problem that the `sse_data.php` file was not served over my HTTPS only reverse proxy.
Not sure why.

Then I tried using the server directly without proxy and over HTTP.
That worked with Chrome but Firefox had an error at that line:
https://github.com/Forceu/barcodebuddy/blob/2d798602baf5d16c6cf09d8b9720d6b02785783a/screen.php#L258
Somehow the content.style did not exist (in the DOM)?

**Comment by Forceu** [comment]
@Kylespamaccoun7 @bsmout are you running Barcode Buddy behind a reverse proxy as well?

If yes, please make sure that you setup the webserver to either pass `X-Accel-Buffering` or set proxy buffering off (see [documentation](https://barcodebuddy-documentation.readthedocs.io/en/latest/setup.html#reverse-proxy)). Otherwise the SSE won't work, which is probably the case here.

@lpfann Thanks for letting me know! I don't think it is related to this issue, but I fixed it in https://github.com/Forceu/barcodebuddy/commit/0b87d07ee6291209340ed16e31191d140184bb32

Please try first setting up the reverse proxy as noted in the documentation and if it still does not work, please update to the current commit and let me know if that makes any difference. The docker image `lastest-dev` has been updated with the commit.

**Comment by lpfann** [comment]
Thanks for the fast reply.

> 
> @Kylespamaccoun7 @bsmout are you running Barcode Buddy behind a reverse proxy as well?
> 
> If yes, please make sure that you setup the webserver to either pass `X-Accel-Buffering` or set proxy buffering off (see [documentation](https://barcodebuddy-documentation.readthedocs.io/en/latest/setup.html#reverse-proxy)). Otherwise the SSE won't work, which is probably the case here.
> 
> @lpfann Thanks for letting me know! I don't think it is related to this issue, but I fixed it in [0b87d07](https://github.com/Forceu/barcodebuddy/commit/0b87d07ee6291209340ed16e31191d140184bb32)
> 
> Please try first setting up the reverse proxy as noted in the documentation and if it still does not work, please update to the current commit and let me know if that makes any difference. The docker image `lastest-dev` has been updated with the commit.

I tried the newest dev docker image.
First I head to remove my old default Nginx config for the new `X-Accel-Buffering` option to exist. Is there a better way to introduce new config changes when updating?

But this change still did not work for my reverse proxy set up. I am using Traefik which is buffering by default (I think).
Actually, I am using two cascading traefik proxies in my current setup, maybe they forget passing the header?

**Comment by cyberjacob** [comment]
@Forceu I've just set up Barcode Buddy for the first time, and also found that JS issue. I can confirm that after updating to the `latest-dev` tag in docker the error is fixed.

**Comment by Forceu** [comment]
Perfect, thank you!

**Comment by cyberjacob** [comment]
Just to confirm, is it expected to have a couple of seconds delay between scanning an item and the screen updating? Seems to be 3-4 seconds by my count.

**Comment by Forceu** [comment]
Yes, I noticed that as well, might be related to https://github.com/Forceu/barcodebuddy/commit/37e3086b36be39717ea74821be8b2023c91d36cb. I will open a new issue for that and investigate.
